// This file was generated by img2rs.py

#[allow(dead_code)]
pub const IMAGE_WIDTH: usize = 1080;

#[allow(dead_code)]
pub const IMAGE_HEIGHT: usize = 1080;

#[allow(dead_code)]
pub const IMAGE_MODE: &str = "RGBA";

#[allow(dead_code)]
pub const IMAGE_DATA: &[u8; 4665600] = include_bytes!("icon.rgba");