// This file was generated by img2rs.py

#[allow(dead_code)]
pub const IMAGE_WIDTH: usize = 128;

#[allow(dead_code)]
pub const IMAGE_HEIGHT: usize = 128;

#[allow(dead_code)]
pub const IMAGE_MODE: &str = "RGBA";

#[allow(dead_code)]
pub const IMAGE_DATA: &[u8; 65536] = include_bytes!("icon.rgba");
